### ISSUE TITLE
There is a 100kb limit on keyword dictionaries, not 100,000 terms.

### ISSUE THREAD

**Issue by AveryBaker** [MicrosoftDocs/microsoft-365-docs#1483]
When you create keyword dictionaries the size limitation is 100kb, not 100,000 terms. 
At 1 byte per character the limitation is closer to 100,000 characters.

PowerShell Error Screenshot:
![image](https://user-images.githubusercontent.com/43822956/77484290-221f1200-6df8-11ea-8aab-147e3d113f96.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 196b87de-20ff-37ea-79b8-beb37a1361e0
* Version Independent ID: d3aa9f91-0cec-b9df-6fc7-415242393e3f
* Content: [Create a keyword dictionary - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/create-a-keyword-dictionary?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/create-a-keyword-dictionary.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/create-a-keyword-dictionary.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by chrfox** [comment]
Hi @AveryBaker 
Thanks for your comment, I'll check on this and update the content as appropriate

**Comment by chrfox** [comment]
Hi @AveryBaker 
Thanks for pointing this out, the document has been corrected to reflect 100KB worth of items.

**Comment by AveryBaker** [comment]
@chrfox 

Did this get reverted back? I noticed today the doc still incorrectly says at the top there is a 100,000 term limit. 

"Keyword dictionaries provide simpler management of keywords and at a much larger scale, supporting up to 100,000 terms per dictionary."

https://docs.microsoft.com/en-us/microsoft-365/compliance/create-a-keyword-dictionary?view=o365-worldwide
